# yaml-language-server: $schema=../../schemas/main-schema.json
parameters:
  - &ZERO_ADDRESS "0x0000000000000000000000000000000000000000" # Zero address sentinel
  - &STRATEGY_ID "0x3b0e47226370dd0daa4b28feb910df52f3fa507a32622521ef348962830e24cd" # strategy.mellow.v1

misc:
  # https://metavaults.mellow.finance/deployments.md
  - &VAULT "0x6a37725ca7f4CE81c004c955f7280d5C704a249e"
  - &ASYNC_DEPOSIT_QUEUE "0xe39EED9A454C4918F8d0682062777cB251cd513F" # DepositQueue (wstETH)
  - &SYNC_DEPOSIT_QUEUE "0xECD2Bfe725fa14f5Ed86e9bDcc0eA4b34A4ed522" # SyncDepositQueue (wstETH)
  - &ASYNC_REDEEM_QUEUE "0x095bFAca9f1c6F2B063Cd67C6d6bfcd0c3aaB7b4" # RedeemQueue (wstETH)

deployed:
  l1:
    - &mellowStrategyFactory "0x8Fac09FD82F031D390B94622E2E4baBf16Fd2236"
    - &strategyCallForwarder "0x7305bB45aF91893B7BCaF0Ad8Eae37cb16820Bb8"

l1:
  rpcUrl: MAINNET_REMOTE_RPC_URL # https://ethereum-rpc.publicnode.com
  explorerHostname: api.etherscan.io
  chainId: 1
  explorerTokenEnv: ETHERSCAN_TOKEN
  contracts:
    mellowStrategyFactory:
      name: MellowStrategyFactory
      address: *mellowStrategyFactory
      checks:
        ASYNC_DEPOSIT_QUEUE: *ASYNC_DEPOSIT_QUEUE
        ASYNC_REDEEM_QUEUE: *ASYNC_REDEEM_QUEUE
        STRATEGY_CALL_FORWARDER_IMPLEMENTATION: *strategyCallForwarder
        STRATEGY_ID: *STRATEGY_ID
        SYNC_DEPOSIT_QUEUE: *SYNC_DEPOSIT_QUEUE
        VAULT: *VAULT
    strategyCallForwarder:
      name: StrategyCallForwarder
      address: *strategyCallForwarder
      checks:
        owner: *ZERO_ADDRESS
